<?php
/*
  By Jake Gordon (jakeg)

  Module to enable nice navigation menus
*/

// Implementation of hook_help()
function nice_menus_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      $output = t('Make drop down css/javascript menus for site navigation and admin menus');
      break;
    case 'admin/settings/nice_menus':
      $output = t('<p>This is a simple module that enables the site to have drop down css/javascript menus for site navigation and admin navigation.</p>');
      break;
  }
  return $output;
}

// Implemention of hook_menu()
function nice_menus_menu() {
  // Load the necessary JavaScript on every page
  drupal_add_js(drupal_get_path('module', 'nice_menus').'/nice_menus.js');
  theme_add_style(drupal_get_path('module', 'nice_menus').'/nice_menus.css');
}


// Implementation of hook_settings()
function nice_menus_settings() {
  $form['nice_menus_number'] = array(
    '#type' => 'textfield', 
    '#title' => t('Number of Nice Menus'), 
    '#size' => '2',
    '#description' => t('The total number of independend nice menus you want. You configure them as normal in admin/blocks'),
    '#default_value' => variable_get('nice_menus_number', '2')
  );

  return $form;
}


// Implementation of hook_block().
function nice_menus_block($op = 'list', $delta = 0, $edit = array()) {

  switch ($op) {
    case 'list':
      for ($i=1;$i<=variable_get('nice_menus_number', '2');$i++) {
        $blocks[$i]['info'] = t('Nice Menu '.$i);
      }
      return $blocks;
    break;

    case 'configure':
      $form['nice_menus_menu_'. $delta] = array(
        '#type' => 'textfield', 
        '#title' => t('Menu Tree'), 
        '#description' => t('The menu tree number (ID) from which to show a nice menu. Find out what this is at admin/menu and noting the ID in the URL for the menu you want to use'),
        '#default_value' => variable_get('nice_menus_menu_'. $delta, '0')
      );
      return $form;
    break;

    case 'save':
      variable_set('nice_menus_menu_'. $delta, $edit['nice_menus_menu_'. $delta]);
    break;

    case 'view':
      $block['subject'] = false; // no title for the block
      if ($menu_tree = _nice_menu_tree(variable_get('nice_menus_menu_'. $delta, '0'))) {
        $block['content'] = "<ul class='nice-menu' id='nice-menu-".$delta."'>".$menu_tree."</ul>";
      }
      else $block['content'] = false;

      return $block;
    break;
  }
}


// Private functions below

function _nice_menu_tree($pid = 0) { 
  $menu = menu_get_menu($pid); 
  $output = ''; 

  foreach ($menu['visible'][$pid]['children'] as $mid) {
    if (count($menu['visible'][$mid]['children']) > 0) {
      $output.= "<li class='menuparent'>".menu_item_link($mid); //."</li>";
      $output.= "<ul>";
      $output.= _nice_menu_tree($mid);
      $output.= "</ul>";
      $output.= "</li>";
    } 
    else {
      $output.= "<li>".menu_item_link($mid)."</li>";
    }
  }
  return $output;
}


?>